services:
  proxy:
    image: nginx
    container_name: proxy
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build:
      context: .
    container_name: app
    # env_file:
      # - .env
    environment:
      - NODE_ENV=development
      - PORT=5173
      - HOST=0.0.0.0
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./svelte.config.js:/app/svelte.config.js
    command: npm run dev -- --host
    healthcheck:
      test: echo "fetch('http://localhost:3000/')" | node
      interval: 5s
